# Generated by Django 5.2.2 on 2025-06-09 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_curso', models.CharField(max_length=30)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='aplicacion.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_material', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='aplicacion.curso')),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_subidos', to='aplicacion.profesor')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='id_profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='aplicacion.profesor'),
        ),
    ]
