# Generated by Django 5.2.2 on 2025-06-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='materiales/'),
        ),
    ]
