# Generated by Django 5.2.2 on 2025-06-10 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_entrega'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entrega',
        ),
    ]
