# Generated by Django 5.2.2 on 2025-06-14 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_perfilusuario_rol_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='fecha_subida',
        ),
        migrations.AddField(
            model_name='material',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='requiere_entrega',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='material',
            name='archivo',
            field=models.FileField(upload_to='materiales/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.curso'),
        ),
        migrations.AlterField(
            model_name='material',
            name='id_profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.profesor'),
        ),
        migrations.AlterField(
            model_name='material',
            name='nom_material',
            field=models.CharField(max_length=100),
        ),
    ]
